server:
  port: 9191
spring:
#  zipkin:
#    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
  application:
    name: payment-service
logging:
  file: C:/Users/sheha/Desktop/payment-service.log
