server:
  port: 9192
spring:
#  zipkin:
#    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb2
  application:
    name: order-service
logging:
  file: C:/Users/sheha/Desktop/order-service.log

